modules: 
  - App\Blog\BlogModule

providers:
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Session\SessionServiceProvider
  - Simplex\Renderer\TwigServiceProvider
  - Simplex\Database\DatabaseServiceProvider

middlewares:
    - Simplex\Middleware\TrailingSlashMiddleware
    - Simplex\Middleware\RoutingMiddleware
    - web: 
      - Simplex\Session\SessionMiddleware
    - api: []

database:
  default: sqlite
  databases:
    sqlite:
      connection: sqlite
  connections:
    sqlite:
      type: sqlite
      path: './resources/database.db'
  
